# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-25 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logreg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='quoted_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
