# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-27 15:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logreg', '0003_auto_20180327_0030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='book',
            name='favorite_user',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
