# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-27 19:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logreg', '0005_travel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='alias',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bday',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
